server:
  port: 4000

spring:
  profiles:
    default: local

  application:
    name: lawblocks

  config:
    import:
      - security/application-db.yml
      - security/application-mail.yml

#JWT Secret Key ??
secret:
  key: ${jwt.secret.key}